### ISSUE TITLE
Please remove zipfile

### ISSUE THREAD

**Issue by pcav** [BC-Consulting/bccscbar#1]
This should not go into source.
Thanks!

**Comment by BC-Consulting** [comment]
Hi Paolo,
I'm confused! If I remove the zip file how can anybody know what files are, and are not, included in the distribution? Is there a special convention for folder structure? How is it compatible with the zip file that needs to be provided in the upload plugin page on the QGIS repo?

**Comment by pcav** [comment]
Please have a look to the way other plugins are doing. In short, from the code here you should prepare the zip and upload it to the repo.

**Comment by BC-Consulting** [comment]
Ok, still not sure, but I removed the zip file and its folder. 
On the one or two repos that I've just visited, it seems that lots of auxiliary files (makefile, *.ui,...) share the same folder with the distribution files. Very confusing...

**Comment by pcav** [comment]
You are right. We try to imporve the situation step by step, helping our developers to clean up their stuff.
