### ISSUE TITLE
An empty title creates an image cut at the top

### ISSUE THREAD

**Issue by alesarrett** [BC-Consulting/bccscbar#2]
When a Color Scale Bar is created leaving an empty Title, the upper part of the png is cut exactly at the limit of the bar, cutting also the label of the upper value (see attached image). Maybe a border should be created around the image to avoid that.

![rasterbar_vscalebar](https://cloud.githubusercontent.com/assets/1692316/11911806/6e67c38e-a622-11e5-9b41-e93400ae1ee4.png)

**Comment by BC-Consulting** [comment]
Sorry for long delay... Should now be fixed in V0.12.0 in the QGIS repo
