### ISSUE TITLE
No new menu entry created

### ISSUE THREAD

**Issue by ldesousa** [BC-Consulting/bccscbar#3]
I just installed this plug-in by cloning this repository into the `.qgis2/python/plugins` folder. No new menu entry was created under *Raster*. Is it in a different menu? Or is there something else to the installation?

**Comment by BC-Consulting** [comment]
Hi,

Very sorry for the late reply. I do not monitor this folder very often!

Please be sure that the plugin is installed in:
.qgis2\python\plugins\bccscbar
and that the following files are in that directory:
![folder (click to display)](https://github.com/BC-Consulting/bccscbar/blob/master/support/colourscalebar1.png)

Then, after re-launching QGIS, the plugin is available under:
![menu (click to display)](https://github.com/BC-Consulting/bccscbar/blob/master/support/colourscalebar.png)

Thanks,
Benoit
