### ISSUE TITLE
Plugin not supported by QGIS 3.0.2

### ISSUE THREAD

**Issue by thomascmira** [BC-Consulting/bccscbar#4]
Hi,

I tried to install the bccscbar directly from its zip file on QGIS 3.0.2 after not seeing it in the plugin repository and it seems to not be supported anymore...

 I got the following error message:

> **Couldn't load plugin 'bccscbar' due to an error when calling its classFactory() method** 
> 
> **ModuleNotFoundError: No module named 'PyQt4'** 
> Traceback (most recent call last):
>   File "C:/OSGEO4\~1/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bccscbar\__init__.py", line 64, in classFactory
>     from .bccscbar import bccScBar
>   File "C:/OSGEO4\~1/apps/qgis/./python\qgis\utils.py", line 664, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\bccscbar\bccscbar.py", line 24, in 
>     from PyQt4.QtCore import *
>   File "C:/OSGEO4\~1/apps/qgis/./python\qgis\utils.py", line 664, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'PyQt4'
> 
> 
> **Python version:** 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
> **QGIS version:** 3.0.2-Girona Girona, 307d082e3d 
> 

It would be amazing if this plugin could be upgraded to the new version of QGIS!

Thank you

**Comment by BC-Consulting** [comment]
Hi,

"Colour Scale Bar is a QGIS V2.x plugin."

bccscbar is only available for QGIS versions 2.x.
A port to QGIS versions 3.x will be done in the future.

Regards,
Benoit

**Comment by thomascmira** [comment]
Merci Benoit!
